<!DOCTYPE html>
<html lang="en">
<head>
    <title>
Exception Helper &#x2013; Rethrown Exceptions | Visual Studio Blog - linksfor.dev(s)    </title>
    <meta charset="utf-8">
    <link rel="alternate" type="application/rss+xml" title="Linksfor.dev(s) feed" href="https://linksfor.dev/feed.rss" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google" value="notranslate">
    <link rel="stylesheet" type="text/css" href="/style.css" />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <meta property="og:title" content="Exception Helper &#x2013; Rethrown Exceptions | Visual Studio Blog - linksfor.dev(s)"/>
    <meta property="article:author" content="Andy SterlandPrincipal PM Manager, Visual StudioFollow"/>
    <meta property="og:description" content="Learn how to root cause exceptions quickly with the Exception Helper in Visual Studio."/>
    <meta property="og:type" content="website"/>
    <meta property="og:url" content="https://devblogs.microsoft.com/visualstudio/exception-helper-rethrown-exceptions/"/>

<meta property="og:site_name" content="linksfor.dev(s)" />
</head>
<body>
    <div class="devring" style="background: #222">
        <div style="text-align:center">Explore other dev related sites in this ring. If you would like to join this ring <a href="https://devring.club">click here</a>.</div>
        <div class="grid">
            <div style="display: grid; grid-template-columns: .5fr 1fr 1fr 1fr; text-align: center;">
                <span class="devring-title"><a href="https://devring.club/">devring.club</a></span>
                <a href="https://devring.club/sites/1/prev" class="devring-previous">Previous</a>
                <a href="https://devring.club/random" class="devring-random">Random</a>
                <a href="https://devring.club/sites/1/next" class="devring-next">Next</a>
            </div>
        </div>
    </div>
    <div class="grid">
        <h1>
<a href="/" style="color:inherit">linksfor.dev(s)</a>
        </h1>
        <title>linksfor.dev(s) - Exception Helper &#x2013; Rethrown Exceptions | Visual Studio Blog</title>
<div class="readable">
        <h1>Exception Helper &#x2013; Rethrown Exceptions | Visual Studio Blog</h1>
            <div>by Andy SterlandPrincipal PM Manager, Visual StudioFollow</div>
            <div>Reading time: 5-6 minutes</div>
        <div>Posted here: 30 Apr 2020</div>
        <p><a href="https://devblogs.microsoft.com/visualstudio/exception-helper-rethrown-exceptions/">https://devblogs.microsoft.com/visualstudio/exception-helper-rethrown-exceptions/</a></p>
        <hr/>
<div id="readability-page-1" class="page"><div id="featured"><div><div><div><div><p><img src="https://secure.gravatar.com/avatar/88191247958ac4ad94054c801211313e?s=58&amp;d=mm&amp;r=g" width="58" height="58" alt="Avatar"></p><p>Andy</p></div></div></div><p>April 28th, 2020</p><p>Ever had a bug in an async method that caused an exception? Been frustrated that the debugger doesn’t show you where that exception happened? Or been frustrated when looking at an exception that has an inner exception, but the debugger doesn’t easily show you where that exception was from? Starting from the Visual Studio 2019 16.5 release, the exception helper now contains the original call stack for a rethrown exception. This helps you get to the root cause in your code of any rethrown exceptions. This is especially helpful in the case of async exceptions, which are caught and then re-thrown by framework code.</p><p><a href="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-1.png" data-featherlight="image"> <img src="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-1.png" srcset="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-1.png 628w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-1-300x153.png 300w" sizes="(max-width: 628px) 100vw, 628px"> </a></p><p>The screenshot above is taken from a simple program that’s using the ‘await’ pattern with break on thrown exceptions turned off.</p><pre><span>static</span><span> </span><span>async</span><span> </span><span>Task</span><span> </span><span>Main</span><span>(</span><span>string</span><span>[]</span><span> args</span><span>)</span><span>
</span><span>{</span><span>
&nbsp; &nbsp;</span><span>await</span><span> a</span><span>();</span><span>
</span><span>}</span><span>

</span><span>async</span><span> </span><span>static</span><span> </span><span>Task</span><span> a</span><span>()</span><span>
</span><span>{</span><span>
&nbsp; &nbsp; </span><span>return</span><span> </span><span>await</span><span> b</span><span>();</span><span>
</span><span>}</span><span>

</span><span>async</span><span> </span><span>static</span><span> </span><span>Task</span><span> b</span><span>()</span><span>
</span><span>{</span><span>
&nbsp; &nbsp; </span><span>return</span><span> </span><span>await</span><span> c</span><span>();</span><span>
</span><span>}</span><span>

</span><span>async</span><span> </span><span>static</span><span> </span><span>Task</span><span> c</span><span>()</span><span>
</span><span>{</span><span>
&nbsp; &nbsp; </span><span>string</span><span> s </span><span>=</span><span> </span><span>null</span><span>;</span><span>
&nbsp; &nbsp; </span><span>return</span><span> </span><span>await</span><span> </span><span>Task</span><span>.</span><span>FromResult</span><span>(</span><span>s</span><span>.</span><span>ToLower</span><span>());</span><span>
</span><span>}</span></pre><p>In the example the exception is thrown at <em>s.ToLower()</em> and exception becomes unhandled at <em>await a()</em> and because of how await works in C# that is where the debugger stops. Unfortunately, all the useful information is back in the function <em>c</em>. Now with the changes in Visual Studio 2019 16.5 you can see the call stack from where the exception was originally thrown in the exception helper (screenshot below).</p><p><a href="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/ExceptionHelperSourceLinks-300x229.png" data-featherlight="image"> <img src="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/ExceptionHelperSourceLinks-300x229.png" alt="Image of Exception Helper with Source Links" width="328" height="250" srcset="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/ExceptionHelperSourceLinks-300x229.png 300w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/ExceptionHelperSourceLinks-768x587.png 768w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/ExceptionHelperSourceLinks.png 807w" sizes="(max-width: 328px) 100vw, 328px"> </a></p><p>You can click on each of the <em>Program.cs</em> links and navigate to the source location at the top of the call stack, inside <em>ConsoleApp5.Program.c() </em>in this case, and then set a breakpoint to be hit next time you run the scenario. Then when the breakpoint is hit you will be stopped at the location where the exception originated and where you probably want to debug further and potentially make changes to fix the issue.</p><p>While you can navigate to the right source code with this feature, you can’t use watches to inspect the state of the application exactly as it was when the exception was initially thrown. This is simply because other code has run since then, which could have changed the state of the application. However, if you are using Visual Studio Enterprise using Visual Studio 2019 Enterprise there is another option, IntelliTrace.</p><h2>IntelliTrace</h2><p>With IntelliTrace VS will capture state from your application at certain points, including when exceptions are thrown, and you can go back and inspect that previous state. The easiest way to do this is to look at the Events tab of the diagnostic tools window (it pops up on the right when you F5). In the events tab you’ll see an event for each exception. In this async example each one of the async methods has a corresponding thrown and caught exception event. If you click on any of them IntelliTrace will take the debugger back to that point in time and you can use the watch windows to inspect the state as it was.</p><p><a href="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-2.png" data-featherlight="image"> <img src="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-2.png" srcset="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-2.png 450w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-2-300x271.png 300w" sizes="(max-width: 450px) 100vw, 450px"> </a></p><p>With most exceptions you probably want to go to the first instance as that’s where it was first thrown. It’s worth mentioning that not all the state is captured for every exception. Things such as the locals and parameters are, but if you were to enter new expression in the watch window it might not evaluate. If you want to capture all the state of the application, you should enable the IntelliTrace Snapshots feature. You can do that by going to Tools Options -&gt; IntelliTrace and enabling “IntelliTrace snapshots (managed and native)” as shown below.</p><p><a href="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3.png" data-featherlight="image"> <img src="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3.png" width="742" height="505" srcset="https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3.png 1065w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3-300x204.png 300w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3-1024x697.png 1024w, https://devblogs.microsoft.com/visualstudio/wp-content/uploads/sites/4/2020/04/word-image-3-768x523.png 768w" sizes="(max-width: 742px) 100vw, 742px"> </a></p><p>With IntelliTrace Snapshots the entire state of the application is captured, and you can inspect anything in the application via the locals and watch windows.</p><p>There are more details in our docs at <a href="https://docs.microsoft.com/en-us/visualstudio/debugger/view-historical-application-state?view=vs-2019" target="_blank">https://docs.microsoft.com/en-us/visualstudio/debugger/view-historical-application-state?view=vs-2019</a>.</p><h2>Conclusion</h2><p>Debugging async code is challenging and something that we are committed to improving the experience of in Visual Studio. This feature is a small step on a path to improving that experience. We have more in mind for the future and would love your feedback, and to hear about the challenges you face and how features like this and others may help or not. If you’re interested in taking part in customer research feel out the survey at <a href="https://www.research.net/r/3WNNWV8" target="_blank">https://www.research.net/r/3WNNWV8</a>. You can also reach out to me on twitter at <a href="https://twitter.com/AndySterland" target="_blank">@andysterland</a>.</p><p>Last, but not least, please suggest and vote on features over on Developer Community at <a href="https://developercommunity.visualstudio.com/content/idea/post.html?space=8" target="_blank">https://developercommunity.visualstudio.com/content/idea/post.html?space=8</a>.</p><p>Look forward to hearing your feedback!</p></div></div></div></div>
    </div>
    <footer>
        <div>created by buildstarted &copy; 2020 <a href="/about">about</a></div>
        <div>Share this page on social media: copy and paste this url https://linksfor.dev/</div>
        <div>If you prefer RSS: <a href="https://linksfor.dev/feed.xml">https://linksfor.dev/feed.xml</a></div>
        <div>Customer satisfaction guaranteed to be optional.</div>
    </footer>
    
    <script async defer>
        _dna = window._dna || {};
        _dna.siteId = "linksfor.devs";
        _dna.outlink = true;

        (function() {
            let dna = document.createElement('script');
            dna.type = 'text/javascript';
            dna.async = true;
            dna.src = '//dna.buildstarted.com/t.js';
            let s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(dna, s);
        })();
    </script>
    <noscript><img src="//dna.buildstarted.com/g?siteId=linksfor.devs"/></noscript>
</body>
</html>